"""Synthetic Play-style clickstream generator.

Produces a parquet file per month under data/raw/. Each row is one event
with a user, session, timestamp, event_type, and dimensional keys. Events
are generated by a persona-driven Poisson process perturbed by a global
initiative calendar.

This is not a behavioral simulator — it is a data-shape simulator. The goal
is to create a dataset where initiatives leave detectable fingerprints in
the aggregate metrics that a downstream attribution agent can identify.
"""

from __future__ import annotations

import random
import uuid
from datetime import date, datetime, timedelta
from pathlib import Path

import numpy as np
import pandas as pd

from .. import config
from .personas import assign_persona


# ---------------------------------------------------------------------------
# User provisioning
# ---------------------------------------------------------------------------


def build_users(rng: np.random.Generator) -> pd.DataFrame:
    """Create the user catalog: one row per user with static dimensions."""
    persona_ids = list(config.PERSONAS.keys())
    persona_weights = np.array([config.PERSONAS[p]["share"] for p in persona_ids])
    persona_weights /= persona_weights.sum()

    users = []
    for i in range(config.NUM_USERS):
        persona = rng.choice(persona_ids, p=persona_weights)
        market = rng.choice(config.MARKETS, p=config.MARKET_WEIGHTS)
        category = rng.choice(config.CATEGORIES, p=config.CATEGORY_WEIGHTS)
        segment = rng.choice(config.SEGMENTS, p=config.SEGMENT_WEIGHTS)
        users.append(
            {
                "user_id": f"u_{i:06d}",
                "persona": persona,
                "market": market,
                "category": category,
                "segment": segment,
                # activation staggers uniformly across the first 60 days so
                # the "new user" cohort makes sense
                "activated_on": config.START_DATE
                + timedelta(days=int(rng.integers(0, 60))),
            }
        )
    return pd.DataFrame(users)


# ---------------------------------------------------------------------------
# Initiative lookup
# ---------------------------------------------------------------------------


def active_initiatives(
    day: date, market: str, category: str
) -> list[dict]:
    """Return all initiatives active on `day` that apply to this dimension."""
    out = []
    for init in config.INITIATIVES:
        if not (init["start"] <= day <= init["end"]):
            continue
        if init["market"] is not None and init["market"] != market:
            continue
        if init["category"] is not None and init["category"] != category:
            continue
        out.append(init)
    return out


def initiative_event_multiplier(
    day: date, market: str, category: str, event_type: str
) -> float:
    """Multiplicative boost on the rate of this event type on this day."""
    mult = 1.0
    for init in active_initiatives(day, market, category):
        mult *= init["effects"].get(event_type, 1.0)
    return mult


def initiative_bot_suppression(day: date) -> float:
    """Return the multiplicative factor on bot session generation rate.

    Used so the 'anti_fraud_push' initiative produces a detectable drop in
    the bot-like persona's session output.
    """
    mult = 1.0
    for init in config.INITIATIVES:
        if not (init["start"] <= day <= init["end"]):
            continue
        mult *= init["effects"].get("bot_session_rate_multiplier", 1.0)
    return mult


# ---------------------------------------------------------------------------
# Event generation
# ---------------------------------------------------------------------------


def _weighted_choice(rng: np.random.Generator, mix: dict[str, float]) -> str:
    """Pick one event type according to `mix` weights."""
    keys = list(mix.keys())
    weights = np.array([mix[k] for k in keys], dtype=float)
    weights /= weights.sum()
    return str(rng.choice(keys, p=weights))


def _month_seasonal_mult(day: date, event_type: str) -> float:
    arr = config.SEASONAL_MONTH_MULT.get(event_type)
    if not arr:
        return 1.0
    return float(arr[day.month - 1])


def generate_session(
    rng: np.random.Generator,
    user: pd.Series,
    day: date,
) -> list[dict]:
    """Generate all events for one user-session on one day."""
    persona = config.PERSONAS[user["persona"]]
    session_id = str(uuid.uuid4())
    # Session start time uniform over the day, duration exponential ~ 5 min
    start_seconds = int(rng.integers(0, 24 * 3600))
    duration_seconds = int(rng.exponential(300))
    started_at = datetime.combine(day, datetime.min.time()) + timedelta(
        seconds=start_seconds
    )
    n_events = max(2, int(rng.poisson(persona["events_per_session_mean"])))

    # Build a rate-adjusted event mix for this day/market/category
    adjusted_mix = {}
    for event_type, base_weight in persona["mix"].items():
        w = base_weight
        w *= initiative_event_multiplier(
            day, user["market"], user["category"], event_type
        )
        w *= _month_seasonal_mult(day, event_type)
        adjusted_mix[event_type] = w

    # Decide conversion outcomes for the session (independent of mix)
    converts = rng.random() < persona["conversion_p"]
    redeems_offer = (
        rng.random() < 0.6 * persona["offer_affinity"]
        and "offer_redeem" in persona["mix"]
    )

    events = []
    for i in range(n_events):
        if i == 0:
            event_type = "session_start"
        elif i == n_events - 1:
            event_type = "session_end"
        else:
            event_type = _weighted_choice(rng, adjusted_mix)

        # Inject guaranteed conversion/redeem events if flagged
        if i == n_events - 2 and converts and "purchase" in persona["mix"]:
            event_type = "purchase"
        if i == n_events - 3 and redeems_offer:
            event_type = "offer_redeem"

        ts = started_at + timedelta(
            seconds=int(duration_seconds * (i / max(n_events - 1, 1)))
        )

        revenue = 0.0
        if event_type == "purchase":
            revenue = round(float(rng.lognormal(mean=1.5, sigma=0.8)), 2)

        events.append(
            {
                "event_id": f"e_{uuid.uuid4().hex[:12]}",
                "user_id": user["user_id"],
                "session_id": session_id,
                "ts": ts,
                "event_type": event_type,
                "market": user["market"],
                "category": user["category"],
                "segment": user["segment"],
                "persona": user["persona"],
                "revenue_usd": revenue,
            }
        )
    return events


def generate_user_events_for_day(
    rng: np.random.Generator, user: pd.Series, day: date
) -> list[dict]:
    """Generate zero or more sessions for this user on this day."""
    # Users aren't active before their activation date
    if day < user["activated_on"]:
        return []

    persona = config.PERSONAS[user["persona"]]
    daily_lambda = persona["sessions_per_day"]

    # Special handling for bot-like persona + anti-fraud initiative
    if user["persona"] == "bot_like":
        daily_lambda *= initiative_bot_suppression(day)

    n_sessions = int(rng.poisson(daily_lambda))
    if n_sessions == 0:
        return []

    out = []
    for _ in range(n_sessions):
        out.extend(generate_session(rng, user, day))
    return out


# ---------------------------------------------------------------------------
# Top-level driver
# ---------------------------------------------------------------------------


def generate_all(users_df: pd.DataFrame, rng: np.random.Generator) -> None:
    """Generate events for all users across the full date range.

    Writes monthly parquet files to data/raw/events_YYYYMM.parquet.
    Uses chunked writes so we never hold more than a month in memory.
    """
    n_days = (config.END_DATE - config.START_DATE).days + 1
    current_month = None
    month_buffer: list[dict] = []

    def flush(month_key):
        if not month_buffer:
            return
        df = pd.DataFrame(month_buffer)
        df["ts"] = pd.to_datetime(df["ts"])
        out_path = config.RAW_DIR / f"events_{month_key}.parquet"
        df.to_parquet(out_path, index=False, compression="snappy")
        print(
            f"  wrote {out_path.name}: {len(df):,} events "
            f"({out_path.stat().st_size / 1024 / 1024:.1f} MB)"
        )

    for day_offset in range(n_days):
        day = config.START_DATE + timedelta(days=day_offset)
        month_key = day.strftime("%Y%m")
        if current_month is None:
            current_month = month_key
        if month_key != current_month:
            flush(current_month)
            month_buffer = []
            current_month = month_key

        for _, user in users_df.iterrows():
            month_buffer.extend(
                generate_user_events_for_day(rng, user, day)
            )

    flush(current_month)


def main() -> None:
    rng = np.random.default_rng(config.SEED)
    random.seed(config.SEED)

    print(f"Longitudinal Data Setup — synthetic clickstream generator")
    print(f"  users: {config.NUM_USERS:,}")
    print(
        f"  date range: {config.START_DATE} → {config.END_DATE} "
        f"({(config.END_DATE - config.START_DATE).days + 1} days)"
    )

    print("\nBuilding user catalog…")
    users_df = build_users(rng)
    users_path = config.RAW_DIR / "users.parquet"
    users_df.to_parquet(users_path, index=False)
    print(f"  wrote {users_path.name}: {len(users_df)} users")

    print("\nGenerating events…")
    generate_all(users_df, rng)

    # Summarize
    total_events = sum(
        pd.read_parquet(p).shape[0]
        for p in config.RAW_DIR.glob("events_*.parquet")
    )
    total_bytes = sum(
        p.stat().st_size for p in config.RAW_DIR.glob("events_*.parquet")
    )
    print(
        f"\nDone. Total: {total_events:,} events, "
        f"{total_bytes / 1024 / 1024:.1f} MB raw parquet"
    )


if __name__ == "__main__":
    main()
